apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: dp-build-run-
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: dp-build-run
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  params:
  - name: repo-url
    value: https://github.com/odowdaibm/dp01-src.git
  - name: image-reference
    #value: registry.dev.svc.cluster.local:5000/dp01-ns/dp01:0.0.1
    value: image-registry.openshift-image-registry.svc:5000/dp01-ns/dp01:0.0.1
  - name: storage-driver
    value: vfs
  - name: tls-verify
    value: "false"
